### ISSUE TITLE
Multiple instances will unpublish each others subscriptions

### ISSUE THREAD

**Issue by JrSchild** [mj1618/serverless-offline-sns#53] opened 2019-01-23 14:28 UTC
Version: `v0.49.0`

**Problem**
We have multiple serverless stacks running inside a docker container. Also there's a localstack instance within the same docker-compose environment. Each sls stack has the following configuration:
```
serverless-offline-sns:
  debug: true
  port: 4002
  host: 0.0.0.0
  sns-subscribe-endpoint: backend-${self:custom.stack}
  sns-endpoint: http://localstack:4575
```
The problem with this set up is that when booting up each serverless-offline-sns instance (inside each stack) will unpublish each other's subscriptions, based on the startup order of the containers.

**Possible solution**
Unpublishing is done based on port, but the `sns-subscribe-endpoint` is not taken into account. A possible solution would be to add this to the `.filter` statement in unsubscribeAll method of index.ts.

Locally I have fixed it by letting each stack listen on a different port. But thought I'd propose my findings here.

**Comment by mj1618** [comment] 2019-07-28 17:27
Thanks for the bug report, happy to accept a pull request on this with the `.filter` added.

**Comment by ricardovf** [comment] 2020-03-04 22:10
Maybe this is related: https://github.com/mj1618/serverless-offline-sns/issues/99

The problem is that when a sls offline start service A, B and C, and latter i kill B, service A will fail to publish to C because B was not unsubscribed when killed...

**Comment by mj1618** [comment] 2021-07-09 15:25
Thank you I have merged chichicuervo's fix

**Closed by mj1618** 2021-07-09 15:25 UTC
